version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 99
    schedule: monthly
  - package-ecosystem: composer
    directory: "/"
    open-pull-requests-limit: 15
    schedule: monthly
